### ISSUE TITLE
EPIC: Abstraction and standardisation of environment variables

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/frms-coe-lib#186]
[env-ver-impact-assessment (1).xlsx](https://github.com/user-attachments/files/17311763/env-ver-impact-assessment.1.xlsx)
Impact assessment and design for abstraction and standardisation of environment variables

## Acceptance Criteria
 - Refactor to implement encapsulation

**Comment by cshezi** [comment]
https://github.com/tazama-lf/docs/blob/cshezi-patch-1/Research-Articles/Encapsulation-of-environment-variables.md
